# Project Mu GitHub Issue Configuration File
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

contact_links:
  - name: ðŸ“ƒ Project Mu Documentation
    url: https://microsoft.github.io/mu/
    about: Goals, principles, repo layout, build instructions, and more.
