# This workflow automatically approves pull requests under certain conditions.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# NOTE: This file uses a reusable workflow. Do not make changes to the file that should be made
#       in the common/reusable workflow.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: Auto Approve Pull Request

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  approval_check:

    permissions:
      pull-requests: write

    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'uefibot'
    uses: microsoft/mu_devops/.github/workflows/AutoApprover.yml@v12.2.0
    secrets: inherit
