# This workflow syncs GitHub labels to the common set of labels defined in Mu DevOps.
#
# All repos should sync at the same time.
#   '0 0,12 * * *''
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: Sync GitHub Labels

on:
  schedule:
    # At minute 0 past hour 0 and 12
    # https://crontab.guru/#0_0,12_*_*_*
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  sync:

    permissions:
      issues: write

    uses: microsoft/mu_devops/.github/workflows/LabelSyncer.yml@v12.2.0
