# This workflow assists with initial triage of new issues by applying
# labels based on data provided in the issue.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: Initial Triage for New Issue

on:
  issues:
    types: [ opened ]

jobs:
  triage:

    permissions:
      issues: write

    uses: microsoft/mu_devops/.github/workflows/IssueTriager.yml@v12.2.0
